# Development docker-compose with individual port exposure
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "5000:5000"
    environment:
      - LINE_CHANNEL_SECRET=${LINE_CHANNEL_SECRET}
      - LINE_CHANNEL_ACCESS_TOKEN=${LINE_CHANNEL_ACCESS_TOKEN}
    volumes:
      - .:/app
    networks:
      - uniqlo-network
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - uniqlo-network
    restart: unless-stopped
    environment:
      - VITE_API_BASE_URL=http://localhost:5000

networks:
  uniqlo-network:
    driver: bridge
