version: '3.8'

services:
  uniqlo-app:
    build: .
    ports:
      - "8080:8080"
    environment:
      # Flask configuration
      - FLASK_ENV=production
      - PORT=8080
      
      # Line Bot configuration (optional)
      - LINE_CHANNEL_SECRET=${LINE_CHANNEL_SECRET:-}
      - LINE_CHANNEL_ACCESS_TOKEN=${LINE_CHANNEL_ACCESS_TOKEN:-}
      
      # Database configuration
      - DATABASE_URL=sqlite:///data/uniqlo_price_finder.db
      - FLASK_SECRET_KEY=${FLASK_SECRET_KEY:-uniqlo-price-finder-secret-key-2024}
      
    volumes:
      # Mount data directory for SQLite database
      - ./data:/app/data
      
    restart: unless-stopped
    networks:
      - uniqlo-network

networks:
  uniqlo-network:
    driver: bridge
