apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: uniqlo-price-finder
  annotations:
    run.googleapis.com/ingress: all
    run.googleapis.com/execution-environment: gen2
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "0"
        autoscaling.knative.dev/maxScale: "10"
        run.googleapis.com/cpu-throttling: "false"
        run.googleapis.com/memory: "1Gi"
        run.googleapis.com/cpu: "1"
    spec:
      containerConcurrency: 100
      timeoutSeconds: 300
      containers:
      - image: us-central1-docker.pkg.dev/PROJECT_ID/uniqlo-app/uniqlo-backend:latest
        ports:
        - name: http1
          containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: FLASK_ENV
          value: "production"
        - name: LINE_CHANNEL_SECRET
          value: "YOUR_LINE_CHANNEL_SECRET"
        - name: LINE_CHANNEL_ACCESS_TOKEN
          value: "YOUR_LINE_CHANNEL_ACCESS_TOKEN"
        resources:
          limits:
            cpu: "1"
            memory: "1Gi"
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
          successThreshold: 1
          failureThreshold: 3
