version: '3.8'

services:
  backend:
    build:
      context: ..
      dockerfile: docker/Dockerfile.backend
    environment:
      - LINE_CHANNEL_SECRET=${LINE_CHANNEL_SECRET}
      - LINE_CHANNEL_ACCESS_TOKEN=${LINE_CHANNEL_ACCESS_TOKEN}
      - FLASK_SECRET_KEY=${FLASK_SECRET_KEY:-uniqlo-price-finder-secret-key-2024}
    volumes:
      - ..:/app
      - ../data:/app/data  # Persist SQLite database
    networks:
      - uniqlo-network
    restart: unless-stopped

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    depends_on:
      - backend
    networks:
      - uniqlo-network
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
      - frontend
    networks:
      - uniqlo-network
    restart: unless-stopped

networks:
  uniqlo-network:
    driver: bridge
